

spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/library"
    username: "root"
    password: "jin951753"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  config:
    activate:
      on-profile: dev
server:
  port: 8081

